# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import image_1_pb2 as image__1__pb2
from . import image_detection_3_pb2 as image__detection__3__pb2


class BrickStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.process = channel.unary_unary(
                '/Brick/process',
                request_serializer=image__1__pb2.Images.SerializeToString,
                response_deserializer=image__detection__3__pb2.ImageDetectionResults.FromString,
                )


class BrickServicer(object):
    """Missing associated documentation comment in .proto file."""

    def process(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrickServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'process': grpc.unary_unary_rpc_method_handler(
                    servicer.process,
                    request_deserializer=image__1__pb2.Images.FromString,
                    response_serializer=image__detection__3__pb2.ImageDetectionResults.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Brick', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Brick(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Brick/process',
            image__1__pb2.Images.SerializeToString,
            image__detection__3__pb2.ImageDetectionResults.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
